#!/usr/bin/env python3
"""Generate the JSON Schema and the Pydantic models from the TypeScript schema.

ARCHITECTURE.md Section 3 makes ``packages/schema/src/*.ts`` the single source of
truth for every inter-stage contract, and requires both downstream artefacts to
be generated:

* ``packages/schema/schema/score-document.schema.json`` — the only validator used
  at the S6 gate (Section 3.7).
* ``core/audiosheet/schema/*.py`` — Pydantic v2 models used by the Python core.

Neither artefact may be hand-edited. Run ``make schema`` to regenerate and
``make schema-check`` to fail a build on drift.

The TypeScript is written in a deliberately small, declarative subset: type
aliases, interfaces, literal unions, arrays, tuples, parenthesised types and
nullable unions. That subset is parsed here directly, so the generator has no
Node.js dependency (see docs/adr/0004-python-schema-generator.md).

Generator annotations, written in a ``/** ... */`` comment above a type alias or
an interface field:

    @integer        the value is integral (JSON "integer", Python ``int``)
    @minimum <n>    inclusive lower bound
    @maximum <n>    inclusive upper bound

Numeric annotations propagate through arrays, tuples and nullable unions down to
the ``number`` primitives they contain.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Final

REPO_ROOT: Final[Path] = Path(__file__).resolve().parents[1]
TS_SRC_DIR: Final[Path] = REPO_ROOT / "packages" / "schema" / "src"
JSON_SCHEMA_OUT: Final[Path] = (
    REPO_ROOT / "packages" / "schema" / "schema" / "score-document.schema.json"
)
PY_SCHEMA_DIR: Final[Path] = REPO_ROOT / "core" / "audiosheet" / "schema"

#: TypeScript modules parsed for contract types, in dependency order.
TS_MODULES: Final[tuple[str, ...]] = (
    "timing.ts",
    "difficulty.ts",
    "note.ts",
    "chord.ts",
    "part.ts",
    "document.ts",
    "gridTable.ts",
)

#: Types the generated artefacts must cover. Everything reachable from a root is
#: emitted; everything else (renderer-side helper types) is skipped.
ROOTS: Final[tuple[str, ...]] = ("ScoreDocument", "RawNote")

#: Which generated Python module re-exports which types. Every model lives in
#: score_document.py so the generated package has no internal import cycles
#: (note <-> difficulty is cyclic at the TypeScript module level).
PY_REEXPORTS: Final[dict[str, str]] = {
    "timing.py": "timing.ts",
    "note.py": "note.ts",
    "chord.py": "chord.ts",
    "difficulty.py": "difficulty.ts",
}

GENERATED_BANNER: Final[str] = "DO NOT EDIT: generated by scripts/gen_schema.py"


# ---------------------------------------------------------------------------
# Lexer
# ---------------------------------------------------------------------------

TOKEN_PUNCT: Final[str] = "{}[]()<>|&;:,=?."
IDENT_RE: Final[re.Pattern[str]] = re.compile(r"[A-Za-z_$][A-Za-z0-9_$]*")
NUMBER_RE: Final[re.Pattern[str]] = re.compile(r"-?\d+(?:\.\d+)?")


@dataclass(frozen=True)
class Token:
    """A lexical token. ``kind`` is one of doc/ident/string/number/punct/eof."""

    kind: str
    value: str
    line: int


class LexError(RuntimeError):
    """The TypeScript source left the supported subset while lexing."""


def lex(source: str, origin: str) -> list[Token]:
    """Tokenise TypeScript source, keeping ``/** ... */`` comments as doc tokens.

    Args:
        source: File contents.
        origin: File name, used in error messages.

    Returns:
        The token list, terminated by an ``eof`` token.

    Raises:
        LexError: On an unterminated string or comment.
    """
    tokens: list[Token] = []
    i = 0
    line = 1
    n = len(source)

    while i < n:
        ch = source[i]

        if ch == "\n":
            line += 1
            i += 1
            continue
        if ch in " \t\r":
            i += 1
            continue

        if source.startswith("/**", i):
            end = source.find("*/", i + 3)
            if end == -1:
                raise LexError(f"{origin}:{line}: unterminated doc comment")
            tokens.append(Token("doc", source[i + 3 : end], line))
            line += source.count("\n", i, end)
            i = end + 2
            continue

        if source.startswith("/*", i):
            end = source.find("*/", i + 2)
            if end == -1:
                raise LexError(f"{origin}:{line}: unterminated block comment")
            line += source.count("\n", i, end)
            i = end + 2
            continue

        if source.startswith("//", i):
            end = source.find("\n", i)
            i = n if end == -1 else end
            continue

        if ch in "\"'`":
            end = i + 1
            while end < n and source[end] != ch:
                if source[end] == "\\":
                    end += 1
                end += 1
            if end >= n:
                raise LexError(f"{origin}:{line}: unterminated string")
            tokens.append(Token("string", source[i + 1 : end], line))
            line += source.count("\n", i, end)
            i = end + 1
            continue

        number = NUMBER_RE.match(source, i)
        if number is not None and (
            ch.isdigit() or (ch == "-" and _next_is_digit(source, i))
        ):
            tokens.append(Token("number", number.group(0), line))
            i = number.end()
            continue

        ident = IDENT_RE.match(source, i)
        if ident is not None:
            tokens.append(Token("ident", ident.group(0), line))
            i = ident.end()
            continue

        if ch in TOKEN_PUNCT:
            tokens.append(Token("punct", ch, line))
            i += 1
            continue

        # Operators and syntax that only occur in value-level code, which the
        # parser skips wholesale.
        tokens.append(Token("punct", ch, line))
        i += 1

    tokens.append(Token("eof", "", line))
    return tokens


def _next_is_digit(source: str, index: int) -> bool:
    return index + 1 < len(source) and source[index + 1].isdigit()


# ---------------------------------------------------------------------------
# Type model
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class Annotations:
    """Generator annotations attached to a type alias or an interface field."""

    description: str | None = None
    integer: bool = False
    minimum: float | None = None
    maximum: float | None = None

    @property
    def has_bounds(self) -> bool:
        """Return whether either bound is set."""
        return self.minimum is not None or self.maximum is not None


@dataclass(frozen=True)
class TPrimitive:
    """``number``, ``string`` or ``boolean``."""

    name: str


@dataclass(frozen=True)
class TNull:
    """The ``null`` type."""


@dataclass(frozen=True)
class TLiteral:
    """A string or numeric literal type."""

    value: str | int | float


@dataclass(frozen=True)
class TRef:
    """A reference to a named type."""

    name: str


@dataclass(frozen=True)
class TArray:
    """``T[]``."""

    item: TypeNode


@dataclass(frozen=True)
class TTuple:
    """``[A, B]``."""

    items: tuple[TypeNode, ...]


@dataclass(frozen=True)
class TUnion:
    """``A | B | null``."""

    members: tuple[TypeNode, ...]


@dataclass(frozen=True)
class TObject:
    """An inline object type."""

    fields: tuple[Field, ...]


TypeNode = TPrimitive | TNull | TLiteral | TRef | TArray | TTuple | TUnion | TObject


@dataclass(frozen=True)
class Field:
    """One interface member."""

    name: str
    type: TypeNode
    annotations: Annotations
    optional: bool = False


@dataclass
class Alias:
    """``export type Name = ...``."""

    name: str
    type: TypeNode
    annotations: Annotations
    module: str


@dataclass
class Interface:
    """``export interface Name { ... }``."""

    name: str
    fields: list[Field]
    annotations: Annotations
    module: str


Declaration = Alias | Interface


# ---------------------------------------------------------------------------
# Doc-comment annotations
# ---------------------------------------------------------------------------

TAG_RE: Final[re.Pattern[str]] = re.compile(
    r"@(integer|minimum|maximum)(?:\s+(-?[\d.]+))?"
)


def parse_doc(raw: str | None) -> Annotations:
    """Parse a doc comment into description text and generator annotations.

    Args:
        raw: The comment body, without the ``/**`` and ``*/`` delimiters.

    Returns:
        The parsed annotations.
    """
    if raw is None:
        return Annotations()

    lines = [re.sub(r"^\s*\*\s?", "", line) for line in raw.splitlines()]
    body = "\n".join(lines).strip()

    integer = False
    minimum: float | None = None
    maximum: float | None = None
    for match in TAG_RE.finditer(body):
        tag, value = match.group(1), match.group(2)
        if tag == "integer":
            integer = True
        elif tag == "minimum" and value is not None:
            minimum = float(value)
        elif tag == "maximum" and value is not None:
            maximum = float(value)

    stripped = re.sub(r"\s+", " ", TAG_RE.sub("", body)).strip()
    description: str | None = stripped or None
    return Annotations(
        description=description, integer=integer, minimum=minimum, maximum=maximum
    )


# ---------------------------------------------------------------------------
# Parser
# ---------------------------------------------------------------------------


class ParseError(RuntimeError):
    """The TypeScript source left the supported subset while parsing."""


class Parser:
    """Recursive-descent parser for the supported TypeScript subset."""

    def __init__(self, tokens: list[Token], module: str) -> None:
        """Create a parser over ``tokens`` originating from ``module``."""
        self.tokens = tokens
        self.module = module
        self.pos = 0

    # -- token helpers --------------------------------------------------

    def peek(self, offset: int = 0) -> Token:
        """Return the token at ``offset`` from the cursor without consuming it."""
        index = min(self.pos + offset, len(self.tokens) - 1)
        return self.tokens[index]

    def next(self) -> Token:
        """Consume and return the token under the cursor."""
        token = self.peek()
        self.pos += 1
        return token

    def at_punct(self, value: str) -> bool:
        """Return whether the cursor is on punctuation ``value``."""
        token = self.peek()
        return token.kind == "punct" and token.value == value

    def at_ident(self, value: str) -> bool:
        """Return whether the cursor is on identifier ``value``."""
        token = self.peek()
        return token.kind == "ident" and token.value == value

    def expect_punct(self, value: str) -> None:
        """Consume punctuation ``value`` or raise.

        Raises:
            ParseError: When the cursor is not on ``value``.
        """
        token = self.next()
        if token.kind != "punct" or token.value != value:
            raise ParseError(
                f"{self.module}:{token.line}: expected {value!r}, got {token.value!r}"
            )

    # -- declarations ---------------------------------------------------

    def parse_module(self) -> tuple[list[Declaration], str | None]:
        """Parse a whole module.

        Returns:
            The declarations found, and the module's header doc comment if any.
        """
        declarations: list[Declaration] = []
        module_doc: str | None = None
        pending_doc: str | None = None

        while self.peek().kind != "eof":
            token = self.peek()

            if token.kind == "doc":
                self.next()
                if module_doc is None and not declarations:
                    module_doc = token.value
                else:
                    pending_doc = token.value
                continue

            if token.kind == "ident" and token.value == "import":
                self._skip_statement()
                continue

            if token.kind == "ident" and token.value == "export":
                nxt = self.peek(1)
                if (
                    nxt.kind == "ident"
                    and nxt.value == "type"
                    and self._is_type_alias()
                ):
                    self.next()
                    declarations.append(self.parse_alias(pending_doc))
                    pending_doc = None
                    continue
                if nxt.kind == "ident" and nxt.value == "interface":
                    self.next()
                    declarations.append(self.parse_interface(pending_doc))
                    pending_doc = None
                    continue
                # export const / function / * from ... — value level, skipped.
                self._skip_statement()
                pending_doc = None
                continue

            # Anything else at top level is value-level code.
            self._skip_statement()
            pending_doc = None

        return declarations, module_doc

    def _is_type_alias(self) -> bool:
        """Distinguish ``export type X =`` from ``export type { ... } from``."""
        return self.peek(2).kind == "ident" and self.peek(3).value == "="

    def parse_alias(self, doc: str | None) -> Alias:
        """Parse ``type Name = <type>;`` with the cursor on ``type``."""
        self.next()  # 'type'
        name = self.next().value
        self.expect_punct("=")
        node = self.parse_type()
        if self.at_punct(";"):
            self.next()
        return Alias(
            name=name, type=node, annotations=parse_doc(doc), module=self.module
        )

    def parse_interface(self, doc: str | None) -> Interface:
        """Parse ``interface Name { ... }`` with the cursor on ``interface``."""
        self.next()  # 'interface'
        name = self.next().value
        fields = self.parse_object_body()
        return Interface(
            name=name,
            fields=list(fields),
            annotations=parse_doc(doc),
            module=self.module,
        )

    def parse_object_body(self) -> tuple[Field, ...]:
        """Parse ``{ field: Type; ... }`` including per-field doc comments."""
        self.expect_punct("{")
        fields: list[Field] = []
        pending_doc: str | None = None

        while not self.at_punct("}"):
            token = self.peek()
            if token.kind == "eof":
                raise ParseError(f"{self.module}: unterminated object type")
            if token.kind == "doc":
                self.next()
                pending_doc = token.value
                continue
            if token.kind == "punct" and token.value in ";,":
                self.next()
                continue

            name_token = self.next()
            if name_token.kind not in {"ident", "string"}:
                raise ParseError(
                    f"{self.module}:{name_token.line}: expected a field name, "
                    f"got {name_token.value!r}"
                )
            optional = False
            if self.at_punct("?"):
                self.next()
                optional = True
            self.expect_punct(":")
            node = self.parse_type()
            fields.append(
                Field(
                    name=name_token.value,
                    type=node,
                    annotations=parse_doc(pending_doc),
                    optional=optional,
                )
            )
            pending_doc = None
            if self.at_punct(";") or self.at_punct(","):
                self.next()

        self.expect_punct("}")
        return tuple(fields)

    def _skip_statement(self) -> None:
        """Skip a value-level statement, keeping bracket nesting balanced."""
        depth = 0
        while True:
            token = self.next()
            if token.kind == "eof":
                return
            if token.kind == "punct":
                if token.value in "{[(":
                    depth += 1
                elif token.value in "}])":
                    depth -= 1
                    if depth <= 0:
                        return
                elif token.value == ";" and depth == 0:
                    return

    # -- types ----------------------------------------------------------

    def parse_type(self) -> TypeNode:
        """Parse a type expression, allowing a leading ``|``."""
        if self.at_punct("|"):
            self.next()
        members = [self.parse_postfix()]
        while self.at_punct("|"):
            self.next()
            members.append(self.parse_postfix())
        if len(members) == 1:
            return members[0]
        return TUnion(tuple(members))

    def parse_postfix(self) -> TypeNode:
        """Parse a primary type followed by any number of ``[]`` suffixes."""
        node = self.parse_primary()
        while (
            self.at_punct("[")
            and self.peek(1).kind == "punct"
            and self.peek(1).value == "]"
        ):
            self.next()
            self.next()
            node = TArray(node)
        return node

    def parse_primary(self) -> TypeNode:
        """Parse a primary type."""
        if self.at_punct("("):
            self.next()
            node = self.parse_type()
            self.expect_punct(")")
            return node

        if self.at_punct("{"):
            return TObject(self.parse_object_body())

        if self.at_punct("["):
            self.next()
            items: list[TypeNode] = [self.parse_type()]
            while self.at_punct(","):
                self.next()
                items.append(self.parse_type())
            self.expect_punct("]")
            return TTuple(tuple(items))

        token = self.next()

        if token.kind == "string":
            return TLiteral(token.value)

        if token.kind == "number":
            text = token.value
            return TLiteral(int(text) if "." not in text else float(text))

        if token.kind == "ident":
            if token.value in {"number", "string", "boolean"}:
                return TPrimitive(token.value)
            if token.value == "null":
                return TNull()
            if token.value == "undefined":
                return TNull()
            if self.at_punct("[") and self.peek(1).kind == "string":
                # Indexed access: Foo["bar"]. A bare "[]" is an array suffix and
                # belongs to parse_postfix, not here.
                self.next()
                key = self.next()
                self.expect_punct("]")
                return TRef(f'{token.value}["{key.value}"]')
            return TRef(token.value)

        raise ParseError(
            f"{self.module}:{token.line}: unexpected token {token.value!r}"
        )


# ---------------------------------------------------------------------------
# Symbol table
# ---------------------------------------------------------------------------


@dataclass
class Schema:
    """Every declaration parsed from the TypeScript source."""

    declarations: dict[str, Declaration] = field(default_factory=dict)
    order: list[str] = field(default_factory=list)
    module_docs: dict[str, str] = field(default_factory=dict)

    def add(self, declaration: Declaration) -> None:
        """Register a declaration, rejecting duplicates.

        Raises:
            ParseError: When two modules declare the same name.
        """
        if declaration.name in self.declarations:
            existing = self.declarations[declaration.name]
            raise ParseError(
                f"duplicate declaration {declaration.name!r} in "
                f"{declaration.module} and {existing.module}"
            )
        self.declarations[declaration.name] = declaration
        self.order.append(declaration.name)

    def resolve(self, name: str) -> Declaration:
        """Look up a declaration by name, following indexed access.

        Raises:
            ParseError: When the name or the accessed field is unknown.
        """
        if '["' in name:
            owner, _, rest = name.partition('["')
            key = rest.rstrip('"]')
            declaration = self.resolve(owner)
            if not isinstance(declaration, Interface):
                raise ParseError(f"indexed access on non-interface {owner!r}")
            for member in declaration.fields:
                if member.name == key:
                    return Alias(
                        name=name,
                        type=member.type,
                        annotations=member.annotations,
                        module=declaration.module,
                    )
            raise ParseError(f"{owner!r} has no field {key!r}")
        if name not in self.declarations:
            raise ParseError(f"unknown type {name!r}")
        return self.declarations[name]


def parse_all(src_dir: Path) -> Schema:
    """Parse every TypeScript module listed in ``TS_MODULES``.

    Args:
        src_dir: ``packages/schema/src``.

    Returns:
        The populated symbol table.

    Raises:
        SystemExit: When a declared module is missing.
    """
    schema = Schema()
    for module in TS_MODULES:
        path = src_dir / module
        if not path.is_file():
            raise SystemExit(f"missing TypeScript module: {path}")
        tokens = lex(path.read_text(encoding="utf-8"), module)
        declarations, module_doc = Parser(tokens, module).parse_module()
        if module_doc is not None:
            schema.module_docs[module] = module_doc
        for declaration in declarations:
            schema.add(declaration)
    return schema


def referenced_names(node: TypeNode) -> set[str]:
    """Return every named type referenced anywhere inside ``node``."""
    if isinstance(node, TRef):
        return {node.name}
    if isinstance(node, TArray):
        return referenced_names(node.item)
    if isinstance(node, TTuple):
        return set().union(*(referenced_names(item) for item in node.items))
    if isinstance(node, TUnion):
        return set().union(*(referenced_names(member) for member in node.members))
    if isinstance(node, TObject):
        return (
            set().union(*(referenced_names(f.type) for f in node.fields))
            if node.fields
            else set()
        )
    return set()


def reachable(schema: Schema, roots: tuple[str, ...]) -> list[str]:
    """Return the reachable declaration names in dependency-first order.

    Args:
        schema: The parsed symbol table.
        roots: Names to start from.

    Returns:
        Names ordered so that every type appears after everything it references.

    Raises:
        ParseError: When the type graph contains a cycle.
    """
    ordered: list[str] = []
    state: dict[str, str] = {}

    def visit(name: str) -> None:
        mark = state.get(name)
        if mark == "done":
            return
        if mark == "active":
            raise ParseError(f"cyclic type reference through {name!r}")
        state[name] = "active"
        declaration = schema.resolve(name)
        node = declaration.type if isinstance(declaration, Alias) else None
        deps = referenced_names(node) if node is not None else set()
        if isinstance(declaration, Interface):
            deps = set().union(*(referenced_names(f.type) for f in declaration.fields))
        for dep in sorted(deps):
            visit(dep)
        state[name] = "done"
        ordered.append(name)

    for root in roots:
        visit(root)
    return ordered


# ---------------------------------------------------------------------------
# JSON Schema emitter
# ---------------------------------------------------------------------------

JsonSchema = dict[str, object]


def _bounds(annotations: Annotations) -> JsonSchema:
    out: JsonSchema = {}
    if annotations.minimum is not None:
        out["minimum"] = _number(annotations.minimum)
    if annotations.maximum is not None:
        out["maximum"] = _number(annotations.maximum)
    return out


def _number(value: float) -> int | float:
    """Return ``value`` as an int when it is integral, so JSON stays tidy."""
    return int(value) if float(value).is_integer() else value


def json_type(node: TypeNode, annotations: Annotations, schema: Schema) -> JsonSchema:
    """Render a type node as a JSON Schema fragment.

    Args:
        node: The type to render.
        annotations: Annotations that propagate into numeric primitives.
        schema: The symbol table, used to fold literal unions into enums.

    Returns:
        The JSON Schema fragment.
    """
    if isinstance(node, TPrimitive):
        if node.name == "number":
            out: JsonSchema = {"type": "integer" if annotations.integer else "number"}
            out.update(_bounds(annotations))
            return out
        return {"type": "string" if node.name == "string" else "boolean"}

    if isinstance(node, TNull):
        return {"type": "null"}

    if isinstance(node, TLiteral):
        return {"const": node.value}

    if isinstance(node, TRef):
        out = {"$ref": f"#/$defs/{node.name}"}
        if annotations.has_bounds and _is_numeric_alias(node.name, schema):
            out.update(_bounds(annotations))
        return out

    if isinstance(node, TArray):
        return {"type": "array", "items": json_type(node.item, annotations, schema)}

    if isinstance(node, TTuple):
        return {
            "type": "array",
            "prefixItems": [
                json_type(item, annotations, schema) for item in node.items
            ],
            "items": False,
            "minItems": len(node.items),
            "maxItems": len(node.items),
        }

    if isinstance(node, TObject):
        return json_object([*node.fields], schema, description=None)

    if isinstance(node, TUnion):
        enum_values = _literal_union_values(node)
        if enum_values is not None:
            return {"enum": enum_values}
        return {
            "anyOf": [json_type(member, annotations, schema) for member in node.members]
        }

    raise ParseError(f"cannot render {node!r} as JSON Schema")


def _literal_union_values(node: TUnion) -> list[str | int | float | None] | None:
    """Return a union's literal values, or ``None`` if it is not all literals.

    A union of literals renders as a JSON Schema ``enum``, which is both smaller and
    more readable than an ``anyOf`` of ``const`` fragments.

    Args:
        node: The union to inspect.

    Returns:
        The literal values in declaration order, or ``None``.
    """
    values: list[str | int | float | None] = []
    for member in node.members:
        if isinstance(member, TNull):
            values.append(None)
        elif isinstance(member, TLiteral):
            values.append(member.value)
        else:
            return None
    return values


def _is_numeric_alias(name: str, schema: Schema) -> bool:
    declaration = schema.declarations.get(name)
    return (
        isinstance(declaration, Alias)
        and isinstance(declaration.type, TPrimitive)
        and declaration.type.name == "number"
    )


def json_object(
    fields: list[Field], schema: Schema, *, description: str | None
) -> JsonSchema:
    """Render an object type. Every non-optional field is required.

    ``additionalProperties`` is always ``false``: an unexpected key means a
    version mismatch and MUST fail (ARCHITECTURE.md Section 3.7).
    """
    properties: JsonSchema = {}
    required: list[str] = []
    for member in fields:
        fragment = json_type(member.type, member.annotations, schema)
        if member.annotations.description:
            fragment = {"description": member.annotations.description, **fragment}
        properties[member.name] = fragment
        if not member.optional:
            required.append(member.name)

    out: JsonSchema = {"type": "object"}
    if description:
        out["description"] = description
    out["properties"] = properties
    out["required"] = required
    out["additionalProperties"] = False
    return out


def build_json_schema(
    schema: Schema, names: list[str], source_fingerprint: str
) -> JsonSchema:
    """Assemble the complete score-document JSON Schema document."""
    defs: JsonSchema = {}
    for name in names:
        declaration = schema.resolve(name)
        if isinstance(declaration, Interface):
            defs[name] = json_object(
                declaration.fields,
                schema,
                description=declaration.annotations.description,
            )
        else:
            fragment = json_type(declaration.type, declaration.annotations, schema)
            if declaration.annotations.description:
                fragment = {
                    "description": declaration.annotations.description,
                    **fragment,
                }
            defs[name] = fragment

    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://audiosheet.invalid/schema/score-document.schema.json",
        "title": "ScoreDocument",
        "description": (
            "The only inter-stage contract in AudioSheet (INV-4). Generated from "
            "packages/schema/src/*.ts; do not hand-edit."
        ),
        "x-generated-by": "scripts/gen_schema.py",
        "x-source-fingerprint": source_fingerprint,
        "$ref": "#/$defs/ScoreDocument",
        "$defs": defs,
    }


# ---------------------------------------------------------------------------
# Pydantic emitter
# ---------------------------------------------------------------------------


def py_literal(value: str | float) -> str:
    """Render a literal value as Python source."""
    return json.dumps(value) if isinstance(value, str) else repr(value)


def py_type(node: TypeNode, annotations: Annotations, schema: Schema) -> str:
    """Render a type node as a Python type expression.

    Args:
        node: The type to render.
        annotations: Annotations that propagate into numeric primitives.
        schema: The symbol table.

    Returns:
        A Python type expression as source text.
    """
    if isinstance(node, TPrimitive):
        if node.name == "number":
            base = "int" if annotations.integer else "float"
            return _annotated(base, annotations)
        return "str" if node.name == "string" else "bool"

    if isinstance(node, TNull):
        return "None"

    if isinstance(node, TLiteral):
        return f"Literal[{py_literal(node.value)}]"

    if isinstance(node, TRef):
        if annotations.has_bounds and _is_numeric_alias(node.name, schema):
            return _annotated(node.name, annotations)
        return node.name

    if isinstance(node, TArray):
        return f"list[{py_type(node.item, annotations, schema)}]"

    if isinstance(node, TTuple):
        inner = ", ".join(py_type(item, annotations, schema) for item in node.items)
        return f"tuple[{inner}]"

    if isinstance(node, TUnion):
        literals = [m for m in node.members if isinstance(m, TLiteral)]
        has_null = any(isinstance(m, TNull) for m in node.members)
        others = [m for m in node.members if not isinstance(m, TLiteral | TNull)]
        parts: list[str] = []
        if literals:
            values = ", ".join(py_literal(m.value) for m in literals)
            parts.append(f"Literal[{values}]")
        parts.extend(py_type(member, annotations, schema) for member in others)
        if has_null:
            parts.append("None")
        return " | ".join(parts)

    raise ParseError(f"cannot render {node!r} as a Python type")


def _annotated(base: str, annotations: Annotations) -> str:
    if not annotations.has_bounds:
        return base
    constraints: list[str] = []
    if annotations.minimum is not None:
        constraints.append(f"ge={_number(annotations.minimum)}")
    if annotations.maximum is not None:
        constraints.append(f"le={_number(annotations.maximum)}")
    return f"Annotated[{base}, Field({', '.join(constraints)})]"


def _docstring(text: str | None, indent: str, fallback: str) -> list[str]:
    body = text or fallback
    wrapped = body if body.endswith(".") else f"{body}."
    if len(indent) + len(wrapped) + 6 <= 96:
        return [f'{indent}"""{wrapped}"""']
    words = wrapped.split()
    lines: list[str] = []
    current = indent
    for word in words:
        candidate = f"{current} {word}" if current.strip() else f"{indent}{word}"
        if len(candidate) > 92 and current.strip():
            lines.append(current)
            current = f"{indent}{word}"
        else:
            current = candidate
    lines.append(current)
    return [f'{indent}"""', *lines, f'{indent}"""']


def build_pydantic_module(
    schema: Schema, names: list[str], source_fingerprint: str
) -> str:
    """Render the single generated Pydantic module holding every model."""
    lines: list[str] = [
        '"""ScoreDocument contract as Pydantic v2 models.',
        "",
        f"{GENERATED_BANNER}",
        "",
        "Source of truth: packages/schema/src/*.ts (ARCHITECTURE.md Section 3).",
        "Every model forbids unknown keys: an unexpected field means a version",
        "mismatch and MUST fail (Section 3.7).",
        "",
        f"Source fingerprint: {source_fingerprint}",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from typing import Annotated, Literal",
        "",
        "from pydantic import BaseModel, ConfigDict, Field",
        "",
        "__all__ = [",
    ]
    lines.extend(f'    "{name}",' for name in sorted(names))
    lines.extend(["]", ""])

    for name in names:
        declaration = schema.resolve(name)
        lines.append("")
        if isinstance(declaration, Alias):
            rendered = py_type(declaration.type, declaration.annotations, schema)
            if declaration.annotations.description:
                lines.append(f"#: {declaration.annotations.description}")
            lines.append(f"{name} = {rendered}")
            lines.append("")
        else:
            lines.append(f"class {name}(BaseModel):")
            lines.extend(
                _docstring(
                    declaration.annotations.description,
                    "    ",
                    f"{name} contract model",
                )
            )
            lines.append("")
            lines.append('    model_config = ConfigDict(extra="forbid")')
            lines.append("")
            for member in declaration.fields:
                rendered = py_type(member.type, member.annotations, schema)
                if member.optional:
                    lines.append(f"    {member.name}: {rendered} = None")
                else:
                    lines.append(f"    {member.name}: {rendered}")
            lines.append("")

    return "\n".join(lines).rstrip("\n") + "\n"


def build_reexport_module(
    module_name: str, ts_module: str, schema: Schema, names: list[str]
) -> str:
    """Render a thin module re-exporting the types declared in one TS module."""
    exported = [n for n in names if schema.resolve(n).module == ts_module]
    lines = [
        f'"""{ts_module} slice of the ScoreDocument contract.',
        "",
        f"{GENERATED_BANNER}",
        "",
        "Every model lives in score_document.py so that the generated package has",
        "no internal import cycles; this module re-exports its slice for callers",
        "that prefer the narrower import.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
    ]
    if exported:
        lines.append("from audiosheet.schema.score_document import (")
        lines.extend(f"    {name}," for name in sorted(exported))
        lines.append(")")
        lines.append("")
        lines.append("__all__ = [")
        lines.extend(f'    "{name}",' for name in sorted(exported))
        lines.append("]")
    else:
        lines.append("__all__: list[str] = []")
    return "\n".join(lines) + "\n"


def build_schema_init(names: list[str]) -> str:
    """Render ``core/audiosheet/schema/__init__.py``."""
    lines = [
        '"""Generated ScoreDocument contract models.',
        "",
        f"{GENERATED_BANNER}",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from audiosheet.schema.score_document import (",
    ]
    lines.extend(f"    {name}," for name in sorted(names))
    lines.extend([")", "", "__all__ = ["])
    lines.extend(f'    "{name}",' for name in sorted(names))
    lines.append("]")
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------


def source_fingerprint(src_dir: Path) -> str:
    """Return a stable BLAKE3-or-SHA256 fingerprint of the TypeScript sources."""
    payload = b""
    for module in TS_MODULES:
        payload += module.encode("utf-8")
        payload += (src_dir / module).read_bytes()
    try:
        from blake3 import blake3

        return "b3:" + blake3(payload).hexdigest()[:32]
    except ImportError:
        import hashlib

        return "sha256:" + hashlib.sha256(payload).hexdigest()[:32]


def canonical_json(value: object) -> str:
    """Serialise to the project's canonical JSON form (sorted keys, newline)."""
    return (
        json.dumps(value, sort_keys=True, ensure_ascii=False, separators=(",", ":"))
        + "\n"
    )


def pretty_json(value: object) -> str:
    """Serialise to stable, human-readable JSON for files humans read."""
    return json.dumps(value, indent=2, ensure_ascii=False, sort_keys=True) + "\n"


@dataclass
class Artefact:
    """One generated file and its intended content."""

    path: Path
    content: str


def generate(src_dir: Path) -> list[Artefact]:
    """Parse the TypeScript sources and return every artefact to be written."""
    schema = parse_all(src_dir)
    names = reachable(schema, ROOTS)
    fingerprint = source_fingerprint(src_dir)

    artefacts = [
        Artefact(
            JSON_SCHEMA_OUT, pretty_json(build_json_schema(schema, names, fingerprint))
        ),
        Artefact(
            PY_SCHEMA_DIR / "score_document.py",
            build_pydantic_module(schema, names, fingerprint),
        ),
        Artefact(PY_SCHEMA_DIR / "__init__.py", build_schema_init(names)),
    ]
    for module_name, ts_module in PY_REEXPORTS.items():
        artefacts.append(
            Artefact(
                PY_SCHEMA_DIR / module_name,
                build_reexport_module(module_name, ts_module, schema, names),
            )
        )
    return artefacts


def main(argv: list[str] | None = None) -> int:
    """Entry point.

    Args:
        argv: Command-line arguments; ``sys.argv[1:]`` when ``None``.

    Returns:
        Process exit status: 0 on success, 1 on drift under ``--check``.
    """
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the generated files are up to date; write nothing",
    )
    args = parser.parse_args(argv)

    artefacts = generate(TS_SRC_DIR)

    if args.check:
        stale = [
            a.path
            for a in artefacts
            if not a.path.is_file() or a.path.read_text(encoding="utf-8") != a.content
        ]
        if stale:
            for path in stale:
                print(f"stale: {path.relative_to(REPO_ROOT)}", file=sys.stderr)
            print("run `make schema` to regenerate", file=sys.stderr)
            return 1
        print(f"schema up to date ({len(artefacts)} artefacts)")
        return 0

    for artefact in artefacts:
        artefact.path.parent.mkdir(parents=True, exist_ok=True)
        artefact.path.write_text(artefact.content, encoding="utf-8")
        print(f"wrote {artefact.path.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
