"""difficulty.ts slice of the ScoreDocument contract.

DO NOT EDIT: generated by scripts/gen_schema.py

Every model lives in score_document.py so that the generated package has
no internal import cycles; this module re-exports its slice for callers
that prefer the narrower import.
"""

from __future__ import annotations

from audiosheet.schema.score_document import (
    DifficultyFlags,
    DifficultyLevel,
    DifficultyProfile,
    DropReason,
    OrnamentPolicy,
    QuantizeWeights,
    SalienceWeights,
    SwingNotation,
    TabWeights,
)

__all__ = [
    "DifficultyFlags",
    "DifficultyLevel",
    "DifficultyProfile",
    "DropReason",
    "OrnamentPolicy",
    "QuantizeWeights",
    "SalienceWeights",
    "SwingNotation",
    "TabWeights",
]
