"""note.ts slice of the ScoreDocument contract.

DO NOT EDIT: generated by scripts/gen_schema.py

Every model lives in score_document.py so that the generated package has
no internal import cycles; this module re-exports its slice for callers
that prefer the narrower import.
"""

from __future__ import annotations

from audiosheet.schema.score_document import (
    Accidental,
    Alter,
    Articulation,
    Dots,
    DurationRational,
    Dynamic,
    Finger,
    NotatedType,
    Note,
    RawNote,
    Rest,
    SlurRef,
    Step,
    TabPosition,
    TabTechnique,
    TieRole,
    TranscriptionModel,
    TupletSpec,
)

__all__ = [
    "Accidental",
    "Alter",
    "Articulation",
    "Dots",
    "DurationRational",
    "Dynamic",
    "Finger",
    "NotatedType",
    "Note",
    "RawNote",
    "Rest",
    "SlurRef",
    "Step",
    "TabPosition",
    "TabTechnique",
    "TieRole",
    "TranscriptionModel",
    "TupletSpec",
]
