"""ScoreDocument contract as Pydantic v2 models.

DO NOT EDIT: generated by scripts/gen_schema.py

Source of truth: packages/schema/src/*.ts (ARCHITECTURE.md Section 3).
Every model forbids unknown keys: an unexpected field means a version
mismatch and MUST fail (Section 3.7).

Source fingerprint: b3:22f760ceb187ebe44c42d53597c63ffd
"""

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field

__all__ = [
    "Accidental",
    "Alter",
    "Articulation",
    "BarreSpec",
    "Beat",
    "ChordEvent",
    "ChordQuality",
    "ChordSource",
    "Clef",
    "ClefSign",
    "Device",
    "Diagnostic",
    "Diagnostics",
    "DifficultyFlags",
    "DifficultyLevel",
    "DifficultyProfile",
    "DocumentStats",
    "Dots",
    "DropReason",
    "DurationRational",
    "Dynamic",
    "Finger",
    "Instrument",
    "KeyEstimate",
    "KeyRegion",
    "Measure",
    "Mode",
    "ModelRecord",
    "NotatedType",
    "Note",
    "OrnamentPolicy",
    "PageSize",
    "Part",
    "PartKind",
    "PartNotation",
    "ProcessingStep",
    "Provenance",
    "QuantizeWeights",
    "RawNote",
    "RenderDirectives",
    "RenderTarget",
    "Rest",
    "SalienceWeights",
    "ScoreDocument",
    "Seconds",
    "SlurRef",
    "SourceFormat",
    "SourceInfo",
    "StemName",
    "Step",
    "SwingNotation",
    "SwingSpec",
    "TabPosition",
    "TabTechnique",
    "TabWeights",
    "TempoEvent",
    "Ticks",
    "TieRole",
    "TimeSignatureEvent",
    "TimingGrid",
    "TranscriptionModel",
    "Transposition",
    "Tuning",
    "TupletSpec",
    "Voicing",
    "VoicingInstrument",
]


#: Notation-domain time.
Ticks = int


class Diagnostic(BaseModel):
    """Diagnostic contract model."""

    model_config = ConfigDict(extra="forbid")

    code: str
    message: str
    tick: Ticks | None


class DocumentStats(BaseModel):
    """DocumentStats contract model."""

    model_config = ConfigDict(extra="forbid")

    raw_note_count: Annotated[int, Field(ge=0)]
    rendered_note_count: Annotated[int, Field(ge=0)]
    dropped_note_count: Annotated[int, Field(ge=0)]
    mean_quantize_shift_ticks: float
    mean_confidence: Annotated[float, Field(ge=0, le=1)]
    transcription_frame_ms: Annotated[float, Field(ge=0)]


class Diagnostics(BaseModel):
    """Diagnostics contract model."""

    model_config = ConfigDict(extra="forbid")

    errors: list[Diagnostic]
    warnings: list[Diagnostic]
    stats: DocumentStats


DifficultyLevel = Literal["simple", "medium", "complex"]


#: How ornaments (trills, mordents, grace notes) are treated. Section 2.0's profile table lists this parameter; Section 3.5's interface omitted it, so it is added here — dropping it would lose normative information.
OrnamentPolicy = Literal["strip", "grace_only", "all"]


class QuantizeWeights(BaseModel):
    """QuantizeWeights contract model."""

    model_config = ConfigDict(extra="forbid")

    alpha: float
    beta: float
    gamma: float
    delta: float


class SalienceWeights(BaseModel):
    """SalienceWeights contract model."""

    model_config = ConfigDict(extra="forbid")

    conf: float
    metric: float
    dur: float
    pitch: float
    energy: float
    contour: float
    harm: float


SwingNotation = Literal["flatten", "directive", "literal"]


TabTechnique = Literal["hammer_on", "pull_off", "slide_up", "slide_down", "slide_legato", "bend", "release", "prebend", "tap", "slap", "pop", "natural_harmonic", "pinch_harmonic"]


class TabWeights(BaseModel):
    """TabWeights contract model."""

    model_config = ConfigDict(extra="forbid")

    k_fret: float
    k_open: float
    k_string: float
    k_high: float
    k_move: float
    k_shift: float
    k_stringJump: float
    k_legato: float
    k_time: float
    k_cross: float


class DifficultyProfile(BaseModel):
    """DifficultyProfile contract model."""

    model_config = ConfigDict(extra="forbid")

    id: str
    level: DifficultyLevel
    label: str
    grid_divisions: Annotated[int, Field(ge=1)]
    allow_tuplets: list[Annotated[int, Field(ge=2)]]
    swing_notation: SwingNotation
    min_note_duration_ticks: Ticks
    quantize_weights: QuantizeWeights
    note_budget_nps: Annotated[float, Field(ge=0)] | None
    max_simultaneous_notes: Annotated[int, Field(ge=1)]
    max_voices: Annotated[int, Field(ge=1)]
    chord_max_notes: Annotated[int, Field(ge=1)]
    chord_tone_priority: list[Annotated[int, Field(ge=1, le=13)]]
    salience_weights: SalienceWeights
    pitch_range_semitones: Annotated[int, Field(ge=1)] | None
    max_accidentals_in_key: Annotated[int, Field(ge=0, le=7)] | None
    allow_transposition: bool
    prefer_capo: bool
    guitar_fret_window: tuple[Annotated[int, Field(ge=0, le=24)], Annotated[int, Field(ge=0, le=24)]]
    guitar_max_span: Annotated[int, Field(ge=1)]
    guitar_max_strings_per_chord: Annotated[int, Field(ge=1, le=12)]
    guitar_allow_barre: bool
    guitar_allow_open_strings: bool
    guitar_techniques: list[TabTechnique]
    tab_weights: TabWeights
    parts_max: Annotated[int, Field(ge=1)] | None
    drum_kit_subset: list[str]
    ornaments: OrnamentPolicy
    show_dynamics: bool
    show_fingerings: bool
    show_chord_diagrams: bool
    use_repeat_signs: bool


Mode = Literal["major", "minor"]


class KeyRegion(BaseModel):
    """KeyRegion contract model."""

    model_config = ConfigDict(extra="forbid")

    tick_on: Ticks
    tick_off: Ticks
    tonic_pc: Annotated[int, Field(ge=0, le=11)]
    mode: Mode
    fifths: Annotated[int, Field(ge=-7, le=7)]
    confidence: Annotated[float, Field(ge=0, le=1)]


class KeyEstimate(BaseModel):
    """KeyEstimate contract model."""

    model_config = ConfigDict(extra="forbid")

    tonic_pc: Annotated[int, Field(ge=0, le=11)]
    mode: Mode
    fifths: Annotated[int, Field(ge=-7, le=7)]
    confidence: Annotated[float, Field(ge=0, le=1)]
    regions: list[KeyRegion]


Alter = Literal[-2, -1, 0, 1, 2]


ChordQuality = Literal["maj", "min", "dim", "aug", "sus2", "sus4", "maj6", "min6", "dom7", "maj7", "min7", "min7b5", "dim7", "aug7", "9", "maj9", "min9", "11", "13", "5", "none"]


ChordSource = Literal["audio", "symbolic", "fused"]


#: Audio-domain time, absolute from the start of the decoded, untrimmed audio.
Seconds = float


Step = Literal["C", "D", "E", "F", "G", "A", "B"]


class BarreSpec(BaseModel):
    """BarreSpec contract model."""

    model_config = ConfigDict(extra="forbid")

    fret: Annotated[int, Field(ge=1, le=24)]
    from_string: Annotated[int, Field(ge=1, le=12)]
    to_string: Annotated[int, Field(ge=1, le=12)]


Finger = Literal[1, 2, 3, 4, "T", "barre"] | None


VoicingInstrument = Literal["guitar", "bass", "ukulele", "piano"]


class Voicing(BaseModel):
    """Voicing contract model."""

    model_config = ConfigDict(extra="forbid")

    id: str
    instrument: VoicingInstrument
    frame: list[Annotated[int, Field(ge=-1, le=24)] | None]
    fingering: list[Finger]
    position: Annotated[int, Field(ge=0, le=24)]
    span: Annotated[int, Field(ge=0)]
    barre: BarreSpec | None
    open_strings: Annotated[int, Field(ge=0)]
    is_common_shape: bool
    shape_name: str | None
    score: float
    diagram_id: str | None
    left_hand: list[Annotated[int, Field(ge=0, le=127)]] | None
    right_hand: list[Annotated[int, Field(ge=0, le=127)]] | None


class ChordEvent(BaseModel):
    """ChordEvent contract model."""

    model_config = ConfigDict(extra="forbid")

    id: str
    tick_on: Ticks
    tick_off: Ticks
    time_on_s: Seconds
    root_pc: Annotated[int, Field(ge=0, le=11)]
    root_step: Step
    root_alter: Alter
    quality: ChordQuality
    bass_pc: Annotated[int, Field(ge=0, le=11)] | None
    extensions: list[Annotated[int, Field(ge=1, le=13)]]
    omissions: list[Annotated[int, Field(ge=1, le=13)]]
    label: str
    confidence: Annotated[float, Field(ge=0, le=1)]
    source: ChordSource
    voicing: Voicing | None


ClefSign = Literal["G", "F", "C", "percussion", "TAB"]


class Clef(BaseModel):
    """Clef contract model."""

    model_config = ConfigDict(extra="forbid")

    staff: Annotated[int, Field(ge=1)]
    sign: ClefSign
    line: Annotated[int, Field(ge=1, le=5)]
    octave_change: Annotated[int, Field(ge=-2, le=2)]


class Tuning(BaseModel):
    """Tuning contract model."""

    model_config = ConfigDict(extra="forbid")

    name: str
    strings: list[Annotated[int, Field(ge=0, le=127)]]
    capo: Annotated[int, Field(ge=0, le=12)]


class Instrument(BaseModel):
    """Instrument contract model."""

    model_config = ConfigDict(extra="forbid")

    midi_program: Annotated[int, Field(ge=0, le=127)]
    midi_channel: Annotated[int, Field(ge=0, le=15)]
    tuning: Tuning | None
    string_count: Annotated[int, Field(ge=1, le=12)] | None
    fret_count: Annotated[int, Field(ge=1, le=36)] | None


Accidental = Literal["natural", "sharp", "flat", "double-sharp", "double-flat", "none"]


Articulation = Literal["staccato", "accent", "tenuto", "marcato", "legato", "vibrato", "harmonic", "palm_mute", "ghost", "dead_note"]


DropReason = Literal["density_budget", "polyphony_cap", "below_min_duration", "voice_cap", "unplayable", "kit_subset", "ornament"]


class DifficultyFlags(BaseModel):
    """DifficultyFlags contract model."""

    model_config = ConfigDict(extra="forbid")

    level: DifficultyLevel
    dropped: bool
    drop_reason: DropReason | None
    quantized: bool
    quantize_shift_ticks: int
    merged_count: Annotated[int, Field(ge=0)]
    simplified_from_chord: bool
    arpeggio_collapsed: bool
    octave_shifted: int
    transposed: int
    swing_flattened: bool
    ornament_stripped: bool
    tuplet_removed: bool
    tab_relaxed: bool
    synthetic: bool
    confidence_low: bool


Dots = Literal[0, 1, 2]


class DurationRational(BaseModel):
    """DurationRational contract model."""

    model_config = ConfigDict(extra="forbid")

    numerator: Annotated[int, Field(ge=1)]
    denominator: Annotated[int, Field(ge=1)]


Dynamic = Literal["pp", "p", "mp", "mf", "f", "ff"]


NotatedType = Literal["whole", "half", "quarter", "eighth", "16th", "32nd", "64th"]


class SlurRef(BaseModel):
    """SlurRef contract model."""

    model_config = ConfigDict(extra="forbid")

    id: str
    role: Literal["start", "stop"]


class TabPosition(BaseModel):
    """TabPosition contract model."""

    model_config = ConfigDict(extra="forbid")

    string: Annotated[int, Field(ge=1, le=12)]
    fret: Annotated[int, Field(ge=-1, le=24)]
    finger: Finger
    is_barre_root: bool
    position: Annotated[int, Field(ge=0, le=24)]


TieRole = Literal["none", "start", "stop", "continue"]


class TupletSpec(BaseModel):
    """TupletSpec contract model."""

    model_config = ConfigDict(extra="forbid")

    actual: Annotated[int, Field(ge=2)]
    normal: Annotated[int, Field(ge=1)]
    level: Literal[1, 2]


class Note(BaseModel):
    """Note contract model."""

    model_config = ConfigDict(extra="forbid")

    id: str
    origin_ids: list[str]
    tick_on: Ticks
    tick_off: Ticks
    time_on_s: Seconds
    time_off_s: Seconds
    duration_rational: DurationRational | None
    notated_type: NotatedType
    dots: Dots
    tuplet: TupletSpec | None
    midi: Annotated[int, Field(ge=0, le=127)]
    step: Step
    alter: Alter
    octave: Annotated[int, Field(ge=-1, le=9)]
    accidental_display: Accidental
    micro_cents: Annotated[float, Field(ge=-100, le=100)]
    part_id: str
    staff: Annotated[int, Field(ge=1)]
    voice: Annotated[int, Field(ge=1)]
    is_chord_member: bool
    velocity: Annotated[int, Field(ge=1, le=127)]
    dynamic: Dynamic | None
    articulations: list[Articulation]
    tie: TieRole
    slur: SlurRef | None
    tab: TabPosition | None
    techniques: list[TabTechnique]
    bend_semitones: float | None
    salience: Annotated[float, Field(ge=0, le=1)]
    confidence: Annotated[float, Field(ge=0, le=1)]
    flags: DifficultyFlags
    render: bool


PartKind = Literal["pitched", "percussion"]


PartNotation = Literal["standard", "tab", "standard+tab", "percussion"]


class Rest(BaseModel):
    """Rest contract model."""

    model_config = ConfigDict(extra="forbid")

    id: str
    tick_on: Ticks
    tick_off: Ticks
    notated_type: NotatedType
    dots: Dots
    part_id: str
    staff: Annotated[int, Field(ge=1)]
    voice: Annotated[int, Field(ge=1)]
    is_multi_measure: bool
    measure_count: Annotated[int, Field(ge=1)]


StemName = Literal["vocals", "drums", "bass", "guitar", "piano", "other", "mix"]


class Part(BaseModel):
    """Part contract model."""

    model_config = ConfigDict(extra="forbid")

    id: str
    name: str
    abbreviation: str
    stem: StemName
    kind: PartKind
    notation: PartNotation
    clefs: list[Clef]
    staff_count: Annotated[int, Field(ge=1, le=2)]
    transpose_semitones: int
    instrument: Instrument
    present: bool
    loudness_lufs: float
    notes: list[Note]
    rests: list[Rest]
    chords: list[ChordEvent]


class ModelRecord(BaseModel):
    """ModelRecord contract model."""

    model_config = ConfigDict(extra="forbid")

    name: str
    version: str
    sha256: str
    license: str


Device = Literal["cpu", "cuda", "mps", "wasm"]


class ProcessingStep(BaseModel):
    """ProcessingStep contract model."""

    model_config = ConfigDict(extra="forbid")

    stage: str
    version: str
    duration_ms: Annotated[float, Field(ge=0)]
    device: Device
    params_hash: str
    warnings: list[str]


class Provenance(BaseModel):
    """Provenance contract model."""

    model_config = ConfigDict(extra="forbid")

    app_version: str
    models: list[ModelRecord]
    steps: list[ProcessingStep]
    created_at_utc: str
    seed: int


PageSize = Literal["letter", "a4", "screen"]


RenderTarget = Literal["sheet", "tab", "both"]


class RenderDirectives(BaseModel):
    """RenderDirectives contract model."""

    model_config = ConfigDict(extra="forbid")

    target: RenderTarget
    system_breaks: list[Ticks]
    measures_per_system: Annotated[int, Field(ge=1)] | None
    page_size: PageSize
    show_ghost_notes: bool


SourceFormat = Literal["mp3", "wav"]


class SourceInfo(BaseModel):
    """SourceInfo contract model."""

    model_config = ConfigDict(extra="forbid")

    filename: str
    sha256: str
    format: SourceFormat
    duration_s: Seconds
    sample_rate: Annotated[int, Field(ge=1)]
    channels: Annotated[int, Field(ge=1, le=2)]
    gain_db: float
    trim_samples: Annotated[int, Field(ge=0)]
    leading_silence_s: Seconds


class Beat(BaseModel):
    """Beat contract model."""

    model_config = ConfigDict(extra="forbid")

    tick: Ticks
    time_s: Seconds
    beat_in_bar: Annotated[int, Field(ge=1)]
    is_downbeat: bool
    confidence: Annotated[float, Field(ge=0, le=1)]


class Measure(BaseModel):
    """Measure contract model."""

    model_config = ConfigDict(extra="forbid")

    index: int
    tick_start: Ticks
    tick_end: Ticks
    time_start_s: Seconds
    time_end_s: Seconds
    time_signature_ref: Annotated[int, Field(ge=0)]
    implicit: bool


class SwingSpec(BaseModel):
    """SwingSpec contract model."""

    model_config = ConfigDict(extra="forbid")

    enabled: bool
    ratio: Annotated[float, Field(ge=1, le=3)]
    subdivision: Literal[8, 16]


class TempoEvent(BaseModel):
    """TempoEvent contract model."""

    model_config = ConfigDict(extra="forbid")

    tick: Ticks
    time_s: Seconds
    bpm: Annotated[float, Field(ge=1, le=600)]
    confidence: Annotated[float, Field(ge=0, le=1)]


class TimeSignatureEvent(BaseModel):
    """TimeSignatureEvent contract model."""

    model_config = ConfigDict(extra="forbid")

    tick: Ticks
    time_s: Seconds
    measure_index: int
    numerator: Annotated[int, Field(ge=1)]
    denominator: Annotated[int, Field(ge=1)]
    confidence: Annotated[float, Field(ge=0, le=1)]


class TimingGrid(BaseModel):
    """The timing grid: the only legal bridge between seconds and ticks (INV-5)."""

    model_config = ConfigDict(extra="forbid")

    ppq: Literal[960]
    tempo_map: list[TempoEvent]
    time_signatures: list[TimeSignatureEvent]
    beats: list[Beat]
    measures: list[Measure]
    swing: SwingSpec
    anacrusis_ticks: Ticks
    first_downbeat_s: Seconds
    meter_confidence: Annotated[float, Field(ge=0, le=1)]
    tempo_octave_corrected: bool


class Transposition(BaseModel):
    """Transposition contract model."""

    model_config = ConfigDict(extra="forbid")

    semitones: int
    as_capo: bool


class ScoreDocument(BaseModel):
    """ScoreDocument contract model."""

    model_config = ConfigDict(extra="forbid")

    schema_version: Literal["1.0.0"]
    id: str
    fingerprint: str
    source: SourceInfo
    timing: TimingGrid
    key: KeyEstimate
    transposition: Transposition | None
    difficulty: DifficultyProfile
    parts: list[Part]
    render: RenderDirectives
    provenance: Provenance
    diagnostics: Diagnostics


TranscriptionModel = Literal["basic-pitch", "crepe", "drum-cnn", "tabcnn"]


class RawNote(BaseModel):
    """A note event straight out of S3/S4, before any symbolic decision is taken."""

    model_config = ConfigDict(extra="forbid")

    id: str
    stem: StemName
    onset_s: Seconds
    offset_s: Seconds
    midi: Annotated[int, Field(ge=0, le=127)]
    micro_cents: Annotated[float, Field(ge=-100, le=100)]
    velocity: Annotated[int, Field(ge=1, le=127)]
    energy_db: float
    confidence: Annotated[float, Field(ge=0, le=1)]
    model: TranscriptionModel
    octave_corrected: bool
