"""timing.ts slice of the ScoreDocument contract.

DO NOT EDIT: generated by scripts/gen_schema.py

Every model lives in score_document.py so that the generated package has
no internal import cycles; this module re-exports its slice for callers
that prefer the narrower import.
"""

from __future__ import annotations

from audiosheet.schema.score_document import (
    Beat,
    Measure,
    Seconds,
    SwingSpec,
    TempoEvent,
    Ticks,
    TimeSignatureEvent,
    TimingGrid,
)

__all__ = [
    "Beat",
    "Measure",
    "Seconds",
    "SwingSpec",
    "TempoEvent",
    "Ticks",
    "TimeSignatureEvent",
    "TimingGrid",
]
